version: "3.3"
services:
  webapp:
    build: .
    command: gunicorn -w 4 -b 0.0.0.0:5000 hello:app --reload
    #command: flask run --host=0.0.0.0
    environment: 
      - FLASK_APP=hello.py
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=TRUE
    ports:
      - "5000:5000"
    volumes:
      - ./:/root